### PR TITLE
Update qualcomm.json

### PR DESCRIPTION
**Pull request by karnagar**
View configuration change applies to the current conformance submission from Qualcomm.

### CODE REVIEW

**Comment by rpavlik** [comment]
You can actually put extensions newer than the conformance submission, it's not limited to just those.

**Comment by rpavlik** [comment]
I'll merge this now, but please feel free to submit another PR with more extension and blend mode support.

**Comment by karnagar** [comment]
The new conformance submission would be for Qualcomm Snapdragon Spaces. Would I be able to just "rename" the "Qualcomm Retina" to "Spaces"

**Comment by rpavlik** [comment]
In this repo, you can do whatever you like, or have multiple entries, or whatnot. For conformance I don't know if you can rename a product in an updated conformance submission, probably can since there are "undisclosed products" in the graphics API conformance list all the time

**Pull request merged**
